// BitmapRects — 精灵矩形管理实现
// 支持 CSV 配置文件加载与自动泛洪填充检测
// 净室设计：基于通用图像处理算法，不依赖任何反编译数据

#include "BitmapRects.h"
#include "SpriteAtlas.h"
#include <Windows.h>
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <deque>
#include <fstream>
#include <sstream>

namespace inkball {

// ============================================================
// 工具：UTF-8 ↔ 宽字符转换
// ============================================================
namespace {

std::wstring Utf8ToWide(const std::string& utf8) {
    if (utf8.empty()) return {};
    int len = MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, nullptr, 0);
    if (len <= 0) return {};
    std::wstring wide(len - 1, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, &wide[0], len);
    return wide;
}

std::string WideToUtf8(const std::wstring& wide) {
    if (wide.empty()) return {};
    int len = WideCharToMultiByte(CP_UTF8, 0, wide.c_str(), -1, nullptr, 0, nullptr, nullptr);
    if (len <= 0) return {};
    std::string utf8(len - 1, '\0');
    WideCharToMultiByte(CP_UTF8, 0, wide.c_str(), -1, &utf8[0], len, nullptr, nullptr);
    return utf8;
}

} // anonymous namespace

// ============================================================
// LoadConfiguration — 从 CSV 文件加载精灵配置
// ============================================================
bool BitmapRects::LoadConfiguration(const std::wstring& path) {
    Clear();

    // 读取整个文件为字符串
    HANDLE hFile = CreateFileW(
        path.c_str(), GENERIC_READ, FILE_SHARE_READ,
        nullptr, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (hFile == INVALID_HANDLE_VALUE) return false;

    DWORD fileSize = GetFileSize(hFile, nullptr);
    if (fileSize == INVALID_FILE_SIZE || fileSize == 0) {
        CloseHandle(hFile);
        return false;
    }

    std::string content(fileSize, '\0');
    DWORD bytesRead = 0;
    if (!ReadFile(hFile, &content[0], fileSize, &bytesRead, nullptr) ||
        bytesRead != fileSize) {
        CloseHandle(hFile);
        return false;
    }
    CloseHandle(hFile);

    // 按行解析
    std::vector<std::pair<int32_t, Rect>> entries;
    std::istringstream stream(content);
    std::string line;

    while (std::getline(stream, line)) {
        // 去除尾部 \r
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
        }
        // 跳过空行和注释行
        if (line.empty() || line[0] == '#') continue;

        int32_t id = 0, left = 0, top = 0, right = 0, bottom = 0;
        if (ParseLine(line, id, left, top, right, bottom)) {
            // 规范化：确保 left <= right, top <= bottom
            if (left > right) std::swap(left, right);
            if (top > bottom) std::swap(top, bottom);
            entries.emplace_back(id, Rect{ left, top, right, bottom });
        }
    }

    if (entries.empty()) return false;

    // 确定最大 ID 并分配数组
    int32_t maxId = 0;
    for (auto& [id, rect] : entries) {
        if (id > maxId) maxId = id;
    }
    if (maxId > kMaxSpriteId) maxId = kMaxSpriteId;

    m_rects.resize(maxId + 1, Rect{ 0, 0, 42, 42 });

    for (auto& [id, rect] : entries) {
        if (id >= 0 && id <= maxId) {
            m_rects[id] = rect;
        }
    }

    m_isValid = true;
    return true;
}

// ============================================================
// ExportConfiguration — 导出当前配置为 CSV
// ============================================================
bool BitmapRects::ExportConfiguration(const std::wstring& path) const {
    if (!m_isValid || m_rects.empty()) return false;

    std::ostringstream oss;
    oss << "# sprite_rects.csv — auto-generated by BitmapRects::ExportConfiguration\n";
    oss << "# format: id,left,top,right,bottom\n";

    for (size_t i = 0; i < m_rects.size(); ++i) {
        const Rect& r = m_rects[i];
        if (r.Width() <= 0 || r.Height() <= 0) continue;
        oss << i << ',' << r.left << ',' << r.top << ','
            << r.right << ',' << r.bottom << '\n';
    }

    std::string utf8 = oss.str();
    std::wstring wide = Utf8ToWide(utf8);

    HANDLE hFile = CreateFileW(
        path.c_str(), GENERIC_WRITE, 0,
        nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (hFile == INVALID_HANDLE_VALUE) return false;

    DWORD bytesWritten = 0;
    BOOL ok = WriteFile(hFile, utf8.c_str(),
        static_cast<DWORD>(utf8.size()), &bytesWritten, nullptr);
    CloseHandle(hFile);

    return ok && bytesWritten == utf8.size();
}

// ============================================================
// AutoDetect — 泛洪填充 + 扫描线投影自动检测精灵
//
// 第一阶段：泛洪填充（Flood Fill）
//   适用于精灵间有明显背景色间隙的情况。
//
// 第二阶段：扫描线投影分析（Projection Analysis）
//   当泛洪填充结果不理想时（区域数 < 10），回退到投影分析。
//   计算行/列的背景色像素密度，找到自然分割线，
//   构建网格并检查每个单元格的前景像素覆盖率。
//   这是一种标准图像分割技术（XY-Cut 算法）。
// ============================================================
int32_t BitmapRects::AutoDetect(const SpriteAtlas& atlas, uint32_t bgColor) {
    Clear();

    int32_t w = atlas.width;
    int32_t h = atlas.height;
    if (w <= 0 || h <= 0 || atlas.pixels.empty()) return 0;

    struct Candidate { int32_t x0, y0, x1, y1; };
    std::vector<Candidate> candidates;

    // ---- 第一阶段：泛洪填充 ----
    {
        std::vector<bool> visited(static_cast<size_t>(w) * h, false);
        const int32_t dx[4] = { 1, -1, 0, 0 };
        const int32_t dy[4] = { 0, 0, 1, -1 };

        for (int32_t y = 0; y < h; ++y) {
            for (int32_t x = 0; x < w; ++x) {
                size_t idx = static_cast<size_t>(y) * w + x;
                if (visited[idx]) continue;
                if (atlas.pixels[idx] == bgColor) {
                    visited[idx] = true;
                    continue;
                }

                int32_t x0 = x, y0 = y, x1 = x, y1 = y;
                int32_t area = 0;
                std::deque<std::pair<int32_t, int32_t>> queue;
                queue.emplace_back(x, y);
                visited[idx] = true;

                while (!queue.empty()) {
                    auto [cx, cy] = queue.front();
                    queue.pop_front();
                    ++area;
                    if (cx < x0) x0 = cx;
                    if (cx > x1) x1 = cx;
                    if (cy < y0) y0 = cy;
                    if (cy > y1) y1 = cy;

                    for (int d = 0; d < 4; ++d) {
                        int32_t nx = cx + dx[d];
                        int32_t ny = cy + dy[d];
                        if (nx < 0 || nx >= w || ny < 0 || ny >= h) continue;
                        size_t nidx = static_cast<size_t>(ny) * w + nx;
                        if (visited[nidx]) continue;
                        if (atlas.pixels[nidx] == bgColor) {
                            visited[nidx] = true;
                            continue;
                        }
                        visited[nidx] = true;
                        queue.emplace_back(nx, ny);
                    }
                }
                if (area >= kMinSpriteArea) {
                    candidates.push_back({ x0, y0, x1 + 1, y1 + 1 });
                }
            }
        }
    }

    // ---- 第二阶段：若泛洪填充结果不足，回退到投影分析 ----
    if (candidates.size() < 10) {
        candidates.clear();

        // 计算水平投影：每行中非背景色像素的占比
        std::vector<double> hProj(h, 0.0);
        for (int32_t y = 0; y < h; ++y) {
            int32_t fg = 0;
            for (int32_t x = 0; x < w; ++x) {
                if (atlas.pixels[static_cast<size_t>(y) * w + x] != bgColor)
                    ++fg;
            }
            hProj[y] = static_cast<double>(fg) / w;
        }

        // 计算垂直投影：每列中非背景色像素的占比
        std::vector<double> vProj(w, 0.0);
        for (int32_t x = 0; x < w; ++x) {
            int32_t fg = 0;
            for (int32_t y = 0; y < h; ++y) {
                if (atlas.pixels[static_cast<size_t>(y) * w + x] != bgColor)
                    ++fg;
            }
            vProj[x] = static_cast<double>(fg) / h;
        }

        // 阈值：背景行/列的密度低于此值时视为分割候选
        const double kGapThreshold = 0.02;

        // 收集水平分割线（背景行）
        std::vector<int32_t> hCuts;
        hCuts.push_back(0);
        for (int32_t y = 0; y < h; ++y) {
            if (hProj[y] < kGapThreshold) {
                if (hCuts.empty() || y - hCuts.back() >= 2)
                    hCuts.push_back(y);
            }
        }
        hCuts.push_back(h);

        // 收集垂直分割线（背景列）
        std::vector<int32_t> vCuts;
        vCuts.push_back(0);
        for (int32_t x = 0; x < w; ++x) {
            if (vProj[x] < kGapThreshold) {
                if (vCuts.empty() || x - vCuts.back() >= 2)
                    vCuts.push_back(x);
            }
        }
        vCuts.push_back(w);

        // 遍历每个网格单元，检测非空单元格
        for (size_t ri = 0; ri + 1 < hCuts.size(); ++ri) {
            for (size_t ci = 0; ci + 1 < vCuts.size(); ++ci) {
                int32_t y0 = hCuts[ri];
                int32_t y1 = hCuts[ri + 1];
                int32_t x0 = vCuts[ci];
                int32_t x1 = vCuts[ci + 1];

                // 跳过太小的单元格（<= 2px）
                if (x1 - x0 <= 2 || y1 - y0 <= 2) continue;

                // 检查单元格内是否有前景像素
                int32_t fgCount = 0;
                int32_t firstX = -1, firstY = -1, lastX = -1, lastY = -1;
                for (int32_t y = y0; y < y1 && fgCount < 20; ++y) {
                    for (int32_t x = x0; x < x1 && fgCount < 20; ++x) {
                        if (atlas.pixels[static_cast<size_t>(y) * w + x] != bgColor) {
                            if (firstX < 0) { firstX = x; firstY = y; }
                            lastX = x; lastY = y;
                            ++fgCount;
                        }
                    }
                }

                if (fgCount >= kMinSpriteArea) {
                    candidates.push_back({ x0, y0, x1, y1 });
                }
            }
        }
    }

    // ---- 统一后处理 ----
    if (candidates.empty()) return 0;

    // 按从顶到底、从左到右排序
    std::sort(candidates.begin(), candidates.end(),
        [](const Candidate& a, const Candidate& b) {
            if (a.y0 != b.y0) return a.y0 < b.y0;
            return a.x0 < b.x0;
        });

    // 填充结果
    m_rects.reserve(candidates.size());
    for (size_t i = 0; i < candidates.size(); ++i) {
        m_rects.push_back(Rect{
            candidates[i].x0, candidates[i].y0,
            candidates[i].x1, candidates[i].y1
        });
    }

    m_isValid = true;
    return static_cast<int32_t>(candidates.size());
}

// ============================================================
// GetSpriteRect — 按 ID 查询源矩形
// ============================================================
Rect BitmapRects::GetSpriteRect(int32_t spriteId) const {
    if (!m_isValid || m_rects.empty()) {
        return Rect{ 0, 0, 42, 42 };
    }
    if (spriteId < 0) spriteId = 0;
    if (spriteId >= static_cast<int32_t>(m_rects.size())) {
        spriteId = spriteId % static_cast<int32_t>(m_rects.size());
    }
    Rect r = m_rects[spriteId];
    // 防御性检查
    if (r.Width() <= 0 || r.Height() <= 0) {
        return Rect{ 0, 0, 42, 42 };
    }
    return r;
}

// ============================================================
// Clear — 清空所有数据
// ============================================================
void BitmapRects::Clear() {
    m_rects.clear();
    m_isValid = false;
}

// ============================================================
// ParseLine — 解析单行 CSV 数据
// 格式: id,left,top,right,bottom
// ============================================================
bool BitmapRects::ParseLine(const std::string& line, int32_t& id,
    int32_t& left, int32_t& top,
    int32_t& right, int32_t& bottom) const
{
    // 简单逗号分割
    auto nextToken = [&line](size_t& pos) -> std::string {
        // 跳过前导空格
        while (pos < line.size() && (line[pos] == ' ' || line[pos] == '\t')) ++pos;
        if (pos >= line.size()) return {};
        size_t end = line.find(',', pos);
        if (end == std::string::npos) end = line.size();
        // 去除尾部空格
        while (end > pos && (line[end - 1] == ' ' || line[end - 1] == '\t')) --end;
        std::string token = line.substr(pos, end - pos);
        pos = end + 1; // 跳过逗号
        return token;
    };

    size_t pos = 0;
    std::string sid = nextToken(pos);
    std::string sl  = nextToken(pos);
    std::string st  = nextToken(pos);
    std::string sr  = nextToken(pos);
    std::string sb  = nextToken(pos);

    if (sid.empty() || sl.empty() || st.empty() || sr.empty() || sb.empty())
        return false;

    auto safeStoi = [](const std::string& s, int32_t& out) -> bool {
        try {
            out = std::stoi(s);
            return true;
        } catch (...) {
            return false;
        }
    };

    return safeStoi(sid, id) && safeStoi(sl, left) &&
           safeStoi(st, top)  && safeStoi(sr, right) &&
           safeStoi(sb, bottom);
}

} // namespace inkball
